### PR TITLE
PHP7 compatybility

### PR DESCRIPTION
**Pull request by dawjan**
What is status for compatibility with PHP7 ?

### CODE REVIEW

**Comment by bjori** [comment]
We will not be supporting PHP7 in the current PHP driver.

We are in the finishing stages of a completely new MongoDB drivers for PHP5 and HHVM:
https://pecl.php.net/package/mongodb

We'll start working on the PHP7 compatibility for the new driver shortly after having released a stable version of the new driver.
You can follow the tracking ticket for that work here: https://jira.mongodb.org/browse/PHPC-285

**Comment by thawkins** [comment]
While this item is closed

does this not mean that we wont get a version of the PHP MongoDB driver that is compatible with php 5.3-5.6 on php7. does this not mean that all large  PHP/Mongodb applications that are currently delivered on 5.3-5.6 will have to be rewritten for php7 as the mongodb driver is no longer API compatible. 

This is a non-starter for some of use with large code bases.

**Comment by bjori** [comment]
@thawkins That is correct, for better or worse.

What it comes down to is the fact the current pecl/mongo driver has a dark side API that we cannot continue to support in the long run, especially considering the internal changes in PHP7, and our wish to support HHVM in the long-run means we would rather take the hit now, then to do multiple breaks separately.

It shouldn't be a very difficult task to create a small pecl/mongo emulation library ontop of pecl/mongodb -- but we will not be publishing an official library like that as we cannot guarantee backwards compatibility towards the dark corners of the previous pecl/mongo driver.

The new [pecl/mongodb](https://pecl.php.net/package/mongodb) extension already has [beta released](https://github.com/bjori/phongo/releases) and fast closing in on its 1.0.0-stable release.
The [userland library ontop|https://github.com/mongodb-labs/mongo-php-library-prototype] of the extension is catching up and is likely to be release another preview shortly.


The pecl/mongodb 1.0.0 release will support PHP5 while we have an [PHP7](https://github.com/bjori/phongo/tree/PHP7) branch ready to be merged after the initial 1.0.0 release

**Comment by thawkins** [comment]
What do you mean by a "dark side API", the current legacy driver uses the published wire format to talk to the server, having been involved in producing a php only version "mongofill" i'm quite aware of the transformations required to go from the PHP Api to the wire format. 

I find it hard to understand what the barriers are to maintaining compatibility...

**Comment by bjori** [comment]
I was mostly referring to the userland API.
Error reporting is not possible in many of the command helpers, and as MongoDB adds more and more features there is no place for us to put them without breaking the userland API.

Static properties and inheritance of WriteConcern and ReadPreferences are problematic, to say the least.

The MongoDB wire protocol is being phased out in favor of a command driven protocol, so the opcodes are not longer maintained and don't support [readConcern](https://jira.mongodb.org/browse/SERVER-18022) or any new features.

The [SDAM specification](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst) would also have been problematic to implement, along with the [CRUD API](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst), and so on and on.


This wasn't a decision we took lightly. The maintainability and future development is drastically reduced by moving over to the new architecture, while still easily be able to support the new features coming in 3.2 and later versions - not to mention only needing to implement those features once as the we have one shared core library (mongoc) which the HHVM, PHP5 and PHP7 driver all wrap, and then we have PHPLIB that wraps the HHVM, PHP5 and PHP7 driver -- so they all share consistent interface with minimal effort.
This means we will be able to iterate on features much faster. Try them out in PHP packages before phasing them in to become official if they pan out and the community likes them. Providing alternative interface depending on your framework of choice etc.

**Comment by jmikola** [comment]
@thawkins: I think it would be feasible to port mongofill to use the new extensions internally, while still providing a legacy API. This is something I was discussing with the Doctrine folks (e.g. porting [doctrine/mongodb](https://github.com/doctrine/mongodb) to do the same).

https://github.com/mongodb-labs/mongo-php-library-prototype is our new userland library, which is implementing a number of the higher level specs conceived by the MongoDB drivers team (e.g. [CRUD](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst)). It takes advantage of the fact that new extensions have minimal APIs that we can build upon to provide more full-featured libraries, which most users will simply consider the driver. Doctrine and mongofill could very well do the same to meet the needs of legacy applications.

**Comment by thawkins** [comment]
This sounds reasonable. My issue was that we have a strong desire to move
to php7 when it stabilises. To get the x2 performance boost on code not
waiting on BE servers. But we have several large non trivial codebases
written in 5.6 against the old abi. Circa 0.5m lines of code, including a
large ODM simular (but not the same as) doctrine. (Its more like the one in
phalcon) Its taken us about 4-5 years to build it out and stabilise it. So
you can understand the dismay i feel when faced with the requirement to
rewrite to move up. Ironicaly im sat here in singapore at the phpasia conf,
listening to rasmus and pierre telling everybody php7 is very compatible,
and people wont have problems porting to it, when i know that because of
this that is just is not true for us.

**Comment by bjori** [comment]
Upgrading userland application that exclusively uses PHP builtin extensions from PHP5 to 7 isn't that hard.
The bundled extensions were all upgraded in one go during the internal API changes.

Extensions that are not bundled with PHP however need to maintain compatibility with PHP5 and PHP7 as we can't assume the target version. This means we can't just change the code in one sweep to be PHP7 compatible like the bundled extensions did. We have to maintain PHP5 compatibility, which is not all rainbows and unicorns.

I feel your pain migrating your codebase to our new extension. We originally had planned on providing a backwards compatibility library to aid in the upgrade, but concluded that we cannot guarantee compatibility in edge case scenarios, which would then result in worse ghost issues for our users that were lead to believe there was nothing for them to do.

We decided it was better to make a clear cut. Make it obvious action is needed.
The new pecl/mongodb is PHP5 compatible so you could start the migration path already while running your current tests on PHP5 so you are never in doubt if it is PHP7 that causes your test to fail, or if its the migration to pecl/mongodb.

We are more then willing to address any concerns or questions you may have during the upgrade, and welcome all feedback you may have!
The API is 99.5% locked in place -- but if you discover issues, we still have few days until the 1.0.0-stable :)

**Pull request closed without merging**
