### PR TITLE
3.2 changes

### PR DESCRIPTION
**Pull request by derickr**

### CODE REVIEW

**Comment by jmikola** [comment]
LGTM. I have some local test failures on 3.2, but I don't think that has anything to do with your PR.

**Comment by derickr** [comment]
Merged

**Comment by bjori** [comment]
I recommend using the 3.2 GA, not old RC.
The RC has issues with for example bypassDocumentValidation and authentication

**Comment by derickr** [comment]
It's ok - Jeremy is pushing that for the next PR.

**Pull request closed without merging**
