### PR TITLE
PHP-1467: Use endian macros in mini_bson.c functions

### PR DESCRIPTION
**Pull request by jmikola**
https://jira.mongodb.org/browse/PHP-1467

### CODE REVIEW

**Comment by bjori** [comment]
These macros are defined in bson.h
Is mcon/ being "PHP free" no longer issue?

**Comment by bjori** [comment]
nvm. They are also defined in mcon/bson_helpers.h

**Comment by derickr** [comment]
This looks Okay, but have you managed to run tests with this?

**Comment by jmikola** [comment]
@derickr: I have run our own tests with this. The IBM fellow tested on big-endian, as I couldn't find the hardware for that.

**Pull request merged**
