### PR TITLE
Marking myself as no longer active

### PR DESCRIPTION
**Pull request by derickr**

### CODE REVIEW

**Comment by moderndeveloperllc** [comment]
Well that's just plain sad. Good luck with your future projects @derickr! Looks like xdebug is still on your radar.

**Comment by jmikola** [comment]
@moderndeveloperllc: In case you missed it: https://derickrethans.nl/moving-on-from-mongodb.html

**Comment by sgolemon** [comment]
I refuse to merge this commit.

**Comment by jmikola** [comment]
> I refuse to merge this commit.

The irony, of course, is that @derickr has PHP/PECL admin access and can do whatever he damn well pleases with our releases and/or documentation.

**Pull request merged**
