### PR TITLE
PHP 7 for Phongo - A New Hope.

### PR DESCRIPTION
**Pull request by derickr**
https://jira.mongodb.org/browse/PHPC-285

This PR supersedes #136

### CODE REVIEW

**Comment by jmikola** [comment]
LGTM :+1:

**Comment by stof** [comment]
``make coveralls`` fails in the PHP 7 job on Travis though

**Comment by jmikola** [comment]
We're also tracking two memory leaks in [PHPC-500](https://jira.mongodb.org/browse/PHPC-500).

**Comment by jmikola** [comment]
`make coveralls` failure will be tracked in [PHPC-522](https://jira.mongodb.org/browse/PHPC-522).

**Comment by Yanxiaojun** [comment]
/mongodb-1.1.1/src/bson.c:508: error: (Each undeclared identifier is reported only once/mnt/amp/mongodb-1.1.1/src/bson.c:508: error: for each function it appears in.)

**Pull request merged**
