### PR TITLE
PHPC-714: BSON corpus tests

### PR DESCRIPTION
**Pull request by jmikola**
https://jira.mongodb.org/browse/PHPC-714

Also, various corpus test cases currently fail. This is likely due to libbson, so we may want to hold off until the C driver implements these tests. I expect that at least some issues cannot be resolved without breaking BC.

### CODE REVIEW

**Comment by derickr** [comment]
So is this still WIP?

**Comment by jmikola** [comment]
> So is this still WIP?

Changed it to WIP. I need to group the specific failures so we can relay those to the C driver team and then update the tests to XFAIL.

**Comment by jmikola** [comment]
A few XFAIL markers depend on other pull requests:

 * https://github.com/mongodb/mongo-php-driver/pull/504
 * https://github.com/mongodb/mongo-php-driver/pull/505
 * https://github.com/mongodb/mongo-php-driver/pull/506

Some markers depend on unresolved libbson issues, some of which should be addressed in 1.6.0 (see also: [CDRIVER-1947](https://jira.mongodb.org/browse/CDRIVER-1947)).

Lastly, this PR currently only implements the "valid" test cases. I still need to handle the "decodeErrors" tests.

**Comment by jmikola** [comment]
The "decodeErrors" and "parseErrors" tests are now handled by the conversion script and included in the PR, so I'm removing the WIP label.

**Comment by jmikola** [comment]
Rebased with updated XFAIL blocks for other resolved tickets. We may want to hold off on merging this until libbson 1.6.0 is tagged (likely PHPC 1.3.0).

**Comment by jmikola** [comment]
I moved the libbson 1.6.0 upgrade to its own PR (https://github.com/mongodb/mongo-php-driver/pull/511) and added XFAIL blocks to BSON corpus tests that still fail in 1.5.x. This will allow us to merge the corpus tests in our 1.2.x branch.

**Pull request merged**
